### ISSUE TITLE
Suggestion: Change title color

### ISSUE THREAD

**Issue by ninita100** [ninita11/T_one#1]
I think it looks better if the main title is a bit more orange.
The styling rule could be changed like this:

``` css
h1 {
  color: #ed9a0b;
}
```
